@startuml

boundary Starter
control Engine
control CacheLoader #EEE
control Synchronizer #AAA
control CacheScavenger
control CacheKeeper

[-> Starter : onStartup()
activate Starter

Starter -> Engine : start()
activate Engine
Engine -> Engine : init()
Engine -> CacheLoader : load()
activate CacheLoader

CacheLoader -> CacheKeeper

deactivate CacheLoader

Engine -> CacheScavenger : start()
activate CacheScavenger
CacheScavenger -> Engine
deactivate CacheScavenger

CacheScavenger -> CacheScavenger : run()
activate CacheScavenger
CacheScavenger -> CacheKeeper : keep(pack)
deactivate CacheScavenger
CacheScavenger -> CacheKeeper : keep(pack)
activate CacheScavenger
deactivate CacheScavenger

Engine -> Engine : up()

Engine -> Engine : join() 加入集群

Engine -> Synchronizer : start()
activate Synchronizer
Synchronizer -> Engine
deactivate Synchronizer

Synchronizer -> Synchronizer : run()
activate Synchronizer
Synchronizer -> CacheKeeper : keep(pack)
deactivate Synchronizer
Synchronizer -> CacheKeeper : keep(pack)
activate Synchronizer

Engine -> Starter
deactivate Engine

[<- Starter
deactivate Starter

@enduml
