@startuml

boundary Starter
control Engine
control CacheLoader #EEE
control CacheSynchronizer #AAA
control CacheKeeper
entity Cache

[-> Starter : onStartup()
activate Starter

Starter -> Engine : start()
activate Engine

Engine -> Engine : init()

Engine -> Engine : load()
activate Engine

Engine -> CacheLoader : load()
activate CacheLoader

CacheLoader -> CacheKeeper :
activate CacheKeeper

deactivate Engine


CacheKeeper -> Cache : CMD()
deactivate CacheKeeper

deactivate CacheSynchronizer

deactivate CacheLoader

Engine -> Engine : join() 加入集群

Engine -> CacheSynchronizer : start()
activate CacheSynchronizer
CacheSynchronizer -> Engine
deactivate CacheSynchronizer

CacheSynchronizer -> CacheSynchronizer : run()
activate CacheSynchronizer
CacheSynchronizer -> CacheKeeper :
activate CacheKeeper
CacheKeeper -> Cache : CMD()
deactivate CacheKeeper

deactivate CacheSynchronizer

Engine -> Starter
deactivate Engine

[<- Starter
deactivate Starter

@enduml